fm: Add uses_lib flag to match manifest
error: mismatch in the <uses-library> tags between the build system and the manifest:
        - required libraries in build system: []
                         vs. in the manifest: [qcom.fmradio]
        - optional libraries in build system: []
                         vs. in the manifest: []
        - tags in the manifest (out/soong/.intermediates/vendor/qcom/opensource/fm-commonsys/fmapp2/FM2/android_common/manifest_fixer/AndroidManifest.xml):
                <uses-library android:name="qcom.fmradio" android:required="true"/>